name: build bae-tg-app
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches: ['dev']
    types:
      - opened
      - reopened

jobs:
  dev-build:
    if: github.event.pull_request.base.ref == 'refs/heads/main' || contains(github.event.pull_request.head.ref, 'feat')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - v20.12.2
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Set Node options
        run: export NODE_OPTIONS="--max-old-space-size=16384 --expose-gc"
      - run: 'npm install'
      - run: 'npm run build:dev'
      - name: Deploying application to Amazon S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--follow-symlinks'
        env:
          AWS_S3_BUCKET: dev.ditto-app
          AWS_ACCESS_KEY_ID: '${{ secrets.TOMO_AWS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.TOMO_AWS_SECRET_ACCESS_KEY }}'
          AWS_REGION: us-west-1
          SOURCE_DIR: ./dist
      - name: dev Invalidate CloudFront
        if: github.event.pull_request.base.ref == 'refs/heads/main' || contains(github.event.pull_request.head.ref, 'feat')
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E1881X4A3HPP9L
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.TOMO_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOMO_AWS_SECRET_ACCESS_KEY }}
  test-build:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - v20.12.2
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - run: 'npm install'
      - run: 'npm run build:test'
      - name: Deploying application to Amazon S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--follow-symlinks'
        env:
          AWS_S3_BUCKET: test.ditto-app
          AWS_ACCESS_KEY_ID: '${{ secrets.TOMO_AWS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.TOMO_AWS_SECRET_ACCESS_KEY }}'
          AWS_REGION: us-west-1
          SOURCE_DIR: ./dist
      - name: dev Invalidate CloudFront
        if: github.ref == 'refs/heads/test'
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: EXHZTXSHC1WJH
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.TOMO_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOMO_AWS_SECRET_ACCESS_KEY }}
  main-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - v20.12.2
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - run: 'npm install'
      - run: 'npm run build:prod'
      - name: Deploying application to Amazon S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--follow-symlinks'
        env:
          AWS_S3_BUCKET: main.ditto-app
          AWS_ACCESS_KEY_ID: '${{ secrets.TOMO_AWS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.TOMO_AWS_SECRET_ACCESS_KEY }}'
          AWS_REGION: us-west-1
          SOURCE_DIR: ./dist
      - name: prod Invalidate CloudFront
        if: github.ref == 'refs/heads/main'
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E2WVONNJML18O3
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.TOMO_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOMO_AWS_SECRET_ACCESS_KEY }}
